# Utiliza la imagen de OpenJDK 21
FROM openjdk:21-jdk-slim

# Copia y descarga las dependencias de Maven
COPY backtiendavirtual/pom.xml /app/
WORKDIR /app
RUN apt-get update && apt-get install -y maven && mvn dependency:go-offline

# Copia el código fuente y compila el JAR
COPY backtiendavirtual /app
RUN mvn clean package -DskipTests

# Expone el puerto 8080
EXPOSE 8080

# Ejecuta la aplicación usando el archivo JAR generado
CMD ["java", "-jar", "target/backtiendavirtual-0.0.1-SNAPSHOT.jar"]
