version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backtiendavirtual:/app
      - ~/.m2:/root/.m2
      - ./uploads:/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tienda_virtual
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_SQL_DEBUG=debug
      - SPRING_DATASOURCE_SPRING_HTTP_DEBUG=debug
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontTiendaVirtual:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: mysql:8.0.40-debian
    restart: always
    environment:
      MYSQL_DATABASE: tienda_virtual
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
