# Etapa 1: Construcción
FROM node:20.18.0-slim as build
WORKDIR /app
COPY frontTiendaVirtual/package*.json ./
RUN npm install
COPY frontTiendaVirtual ./
RUN npm run build

# Etapa 2: Servir los archivos estáticos con NGINX
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
